name: blobtoolkit
owner: bgruening
description: Identification and isolation non-target data in draft and publicly available genome assemblies.
homepage_url: https://blobtoolkit.genomehubs.org/
long_description: BlobTools2 is a command line program to import a genome assembly together with BLAST, Diamond, read mapping and BUSCO analysis output files to generate a dataset that can be filtered using the command line and/or explored interactively in a web browser using the BlobToolKit Viewer.
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/blobtoolkit
type: unrestricted
categories:
- Sequence Analysis
- Assembly
